### PR TITLE
Package

### PR DESCRIPTION
**Pull request by Toby222**
This turns the codebase into a yarn package, with linting and typing packages as dev dependencies, and some rules and scripts already set up
It also adds back the less files from the original repo, and recompiles them (there was some styling on newly discovered buttons that apparently never got compiled)

All files got refactored quite a bit, probably at loss of some compatibility with old browsers
There should in theory be no unintended side-effects anymore

### CODE REVIEW

**Comment by Toby222** [comment]
Would be nice to get a look-over before merging because I didn't extensively test everything

**Comment by spencers145** [comment]
Opened it up locally to test for issues, immediately got issues. The scene image doesn't change when it's supposed to, it just disappears and nothing replaces it. Additionally, the text never updates below the image. Following exception:
`TypeError: b.ownerDocument is undefined`
which occurs in home.js in the updateMessage function, on the line which reads like so:
`thisSel.animate({ opacity: 1 }, 200).html(h.extraMessages[selectedIndex].message);`
The error occurs in jquery. Not that I know definitively what I'm saying, but I noticed that on the line previous
`const thisSel = $(this);`
thisSel gets defined differently on this branch than on a stable branch - on the stable branch it refers to the small message under the "you are a shark in blah blah whatever", but on this branch it doesn't reference anything.

I should ask, what does yarn do exactly?

**Comment by Toby222** [comment]
> I should ask, what does yarn do exactly?

[yarn](https://yarnpkg.com/) is a package manager, just like [npm](https://www.npmjs.com/) and is used to install packages from remote repositories.
It will only be a difference when used locally and even then remains optional.

> `TypeError: b.ownerDocument is undefined`

That's indeed an error that came from linting, and should be easy to fix.
Namely the linting rules prefer no unnamed functions in the style of 
```js
function (){
   console.log("test");
}```
Now, for most purposes those are equivalent to ```js
() => { console.log("test"); }
```
_Except_ for the "this".
I think it's so that in `function`  it's declared at function definition. In Arrow-Syntax it's dependent on the scope where it is executed. I'm not sure though.
Either way I missed this one when I was replacing the function declarations.

**Comment by spencers145** [comment]
I'll have to do some additional testing today before merging. I'll get back to you on it.

**Comment by Toby222** [comment]
Feedback on the formatting is also fair.

**Pull request merged**
